{"name": "test_order", "status": "broken", "statusDetails": {"message": "TypeError: post() got multiple values for argument 'data'", "trace": "self = <script.test_mtx_order.TestOrder object at 0x000002437BFBBCF8>\n\n    def test_order(self):\n        MtxLogin().login_success(self.session)\n    \n>       res_order = self.order.order(self.session)\n\nscript\\test_mtx_order.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.loginOder.LoginOder object at 0x000002437C09C7B8>\nsession = <requests.sessions.Session object at 0x000002437C09C3C8>\n\n    def order(self, session):\n        data = {\n            'goods_id': '4',\n            'buy_type': 'goods',\n            'stock': '1',\n            'spec': ''\n        }\n    \n>       response = session.post(self.url, session, data=data, headers=HEADERS)\nE       TypeError: post() got multiple values for argument 'data'\n\napi\\loginOder.py:21: TypeError"}, "start": 1599149310131, "stop": 1599149310291, "uuid": "b84f213f-485c-474b-8bc4-4f21b7a25679", "historyId": "5f149e3ac521bd9761cd04d7d8d26275", "testCaseId": "1f02b004fadc5a3e5f88f371700624a2", "fullName": "script.test_mtx_order.TestOrder#test_order", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_mtx_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "LAPTOP-TJH92AQ2"}, {"name": "thread", "value": "27872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_mtx_order"}]}